<?php
$host = 'https://open.rocket.chat'; // Root domain of your Rocket Chat installation.
$token = 'insertTokenHere'; // The token generated by Rocket.Chat. Info on obtaining this is located in README.md.
$mention = '@rickbakker'; // The user(s) that will be mentioned by the bot each time a message is triggered. Spaces can be used to separate users.
$vat = 21; // VAT percentage for EU customers. This is displayed as x% MwSt by the bot and a calculated price (price of server + VAT) will be displayed by the bot. Dutch BTW 21%.
// Reference for VAT rates: https://www.ricksteves.com/travel-tips/money/vat-rates-in-europe

// BOTH of these conditions MUST be fulfilled by a server in order for you to be notified.
$maxPrice = 27; // Maximum price for a server in the auction that you wish to be notified of. Price is in Euros (€).
$minRam = 16; // Minimum amount of RAM (in GB) a server must have in order for you to be notified.

$maxList = 10; // Maximum amount of new servers to show. SETTING THIS VALUE TOO HIGH WILL CAUSE HIGH CPU USAGE ON THE ROCKET.CHAT CLIENT AND SERVER!
$thanks = true; // Whether you wish to give credit to me (the creator of this script) via a HTTP header.
